/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplikasi;

import DAO.TarifDAO;
import Model.Penerima;
import Model.Pengirim;
import Model.Tarif;
import Perhitungan.Perhitungan;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

/**
 *
 * @author user
 */
public class AplikasiPengirimanBarang extends javax.swing.JFrame {

    /**
     * @return the resipaket
     */
    

    private TarifDAO dao = new TarifDAO();
    private Pengirim pengirim = new Pengirim();
    private Penerima penerima = new Penerima();
    private Tarif tarif = new Tarif();
    
    private Perhitungan perhitungan = new Perhitungan();
    private String[] combo = dao.createcombo();
    
    
    
    
    
    /**
     * Creates new form AplikasiPengirimanBarang
     */
    public AplikasiPengirimanBarang() {
        initComponents();
        isiComboBoxTujuan();
        
        
        
    }

    public void isiComboBoxTujuan(){
        dao.scanTarif();
        ArrayList<Tarif> list = new ArrayList<>(dao.getListtarif());
        for (Tarif tarif : list) {
            TujuanDataCombo.addItem(tarif.getProvinsiTujuan());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        NamaPengirimTextField1 = new javax.swing.JTextField();
        PengirimTelpTextField1 = new javax.swing.JTextField();
        AlamatPengirimTextField1 = new javax.swing.JTextField();
        KotaPengirimTextField1 = new javax.swing.JTextField();
        ProvinsiPengirimTextField1 = new javax.swing.JTextField();
        KodePosPengirimTextField1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        NamaPenerimaTextField1 = new javax.swing.JTextField();
        PenerimaTelpTextField1 = new javax.swing.JTextField();
        AlamatPenerimaTextField1 = new javax.swing.JTextField();
        KotaPenerimaTextField1 = new javax.swing.JTextField();
        KodePosPenerimaTextField1 = new javax.swing.JTextField();
        ProvinsiPenerimaTextField1 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        TarifTextField = new javax.swing.JTextField();
        BiayaTextField = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        ResiTextField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        DimensiText = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        NamaPengirimTextField = new javax.swing.JTextField();
        PengirimTelpTextField = new javax.swing.JTextField();
        AlamatPengirimTextField = new javax.swing.JTextField();
        KotaPengirimTextField = new javax.swing.JTextField();
        ProvinsiPengirimTextField = new javax.swing.JTextField();
        KodePosPengirimTextField = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        NamaPenerimaTextField = new javax.swing.JTextField();
        PenerimaTelpTextField = new javax.swing.JTextField();
        AlamatPenerimaTextField = new javax.swing.JTextField();
        KotaPenerimaTextField = new javax.swing.JTextField();
        KodePosPenerimaTextField = new javax.swing.JTextField();
        TujuanDataCombo = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        JenisCombo = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        TesButton = new javax.swing.JButton();
        BeratTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        PanjangText = new javax.swing.JTextField();
        LebarText = new javax.swing.JTextField();
        TinggiText = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        YesAsuransiRadio = new javax.swing.JRadioButton();
        NoAsuransiRadio = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        HargaTextField = new javax.swing.JTextField();
        PembayaranCombo = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        ClearButton = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();

        jLabel30.setText("NAMA PENGIRIM");

        jLabel31.setText("ALAMAT");

        jLabel32.setText("KOTA");

        jLabel33.setText("PROVINSI");

        jLabel34.setText("KODE POS");

        jLabel35.setText("NO. TELEPON");

        NamaPengirimTextField1.setEnabled(false);

        PengirimTelpTextField1.setEnabled(false);
        PengirimTelpTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PengirimTelpTextField1ActionPerformed(evt);
            }
        });

        AlamatPengirimTextField1.setEnabled(false);

        KotaPengirimTextField1.setEnabled(false);

        ProvinsiPengirimTextField1.setEnabled(false);

        KodePosPengirimTextField1.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel35)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34))
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(KodePosPengirimTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KotaPengirimTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(AlamatPengirimTextField1)
                    .addComponent(PengirimTelpTextField1)
                    .addComponent(NamaPengirimTextField1)
                    .addComponent(ProvinsiPengirimTextField1))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(NamaPengirimTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(PengirimTelpTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(AlamatPengirimTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(KotaPengirimTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(ProvinsiPengirimTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(KodePosPengirimTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel36.setText("NAMA PENERIMA");

        jLabel37.setText("NO. TELEPON");

        jLabel38.setText("ALAMAT");

        jLabel39.setText("KOTA");

        jLabel40.setText("PROVINSI");

        jLabel41.setText("KODE POS");

        NamaPenerimaTextField1.setEnabled(false);

        PenerimaTelpTextField1.setEnabled(false);

        AlamatPenerimaTextField1.setEnabled(false);

        KotaPenerimaTextField1.setEnabled(false);

        KodePosPenerimaTextField1.setEnabled(false);
        KodePosPenerimaTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KodePosPenerimaTextField1ActionPerformed(evt);
            }
        });

        ProvinsiPenerimaTextField1.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel40)
                            .addComponent(jLabel41))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(KodePosPenerimaTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE))
                            .addComponent(ProvinsiPenerimaTextField1)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37)
                            .addComponent(jLabel38)
                            .addComponent(jLabel39))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(AlamatPenerimaTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(PenerimaTelpTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NamaPenerimaTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KotaPenerimaTextField1))))
                .addGap(78, 78, 78))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(NamaPenerimaTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(PenerimaTelpTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(AlamatPenerimaTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(KotaPenerimaTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(ProvinsiPenerimaTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(KodePosPenerimaTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel28.setText("Tarif/KG");

        TarifTextField.setEnabled(false);

        BiayaTextField.setEnabled(false);

        jLabel29.setText("Biaya Kirim");

        jLabel27.setText("Nomer Resi");

        ResiTextField.setEnabled(false);

        jLabel23.setText("DIMENSI");

        DimensiText.setEnabled(false);

        jLabel24.setText("CM^3");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TarifTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(18, 18, 18)
                        .addComponent(BiayaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(103, 103, 103)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel23))
                .addGap(42, 42, 42)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(DimensiText)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel24))
                    .addComponent(ResiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TarifTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(ResiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(BiayaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(DimensiText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("DATA PENGIRIMAN");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDialog1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel42)
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NAMA PENGIRIM");

        jLabel2.setText("ALAMAT");

        jLabel3.setText("KOTA");

        jLabel4.setText("PROVINSI");

        jLabel6.setText("KODE POS");

        jLabel7.setText("NO. TELEPON");

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("DATAP ENGIRIM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NamaPengirimTextField)
                            .addComponent(PengirimTelpTextField)
                            .addComponent(AlamatPengirimTextField)
                            .addComponent(KotaPengirimTextField)
                            .addComponent(ProvinsiPengirimTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                            .addComponent(KodePosPengirimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel43)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NamaPengirimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(PengirimTelpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(AlamatPengirimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(KotaPengirimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ProvinsiPengirimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(KodePosPengirimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DATA PENERIMA");

        jLabel8.setText("NAMA PENERIMA");

        jLabel9.setText("NO. TELEPON");

        jLabel10.setText("ALAMAT");

        jLabel11.setText("KOTA");

        jLabel12.setText("PROVINSI");

        jLabel13.setText("KODE POS");

        KodePosPenerimaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KodePosPenerimaTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(76, 76, 76)
                                .addComponent(KodePosPenerimaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TujuanDataCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(KotaPenerimaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                    .addComponent(AlamatPenerimaTextField)
                                    .addComponent(PenerimaTelpTextField)
                                    .addComponent(NamaPenerimaTextField))))
                        .addGap(0, 48, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(NamaPenerimaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(PenerimaTelpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(AlamatPenerimaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(KotaPenerimaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(TujuanDataCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(KodePosPenerimaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
        );

        JenisCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "reguler","cepat","express","tommorow","sameday" }));

        jLabel15.setText("JENIS PAKET");

        TesButton.setText("Hitung");
        TesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TesButtonActionPerformed(evt);
            }
        });

        jLabel14.setText("BERAT");

        jLabel16.setText("PANJANG");

        jLabel17.setText("LEBAR");

        jLabel18.setText("TINGGI");

        LebarText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LebarTextActionPerformed(evt);
            }
        });

        jLabel19.setText("CM");

        jLabel20.setText("CM");

        jLabel21.setText("CM");

        buttonGroup1.add(YesAsuransiRadio);
        YesAsuransiRadio.setText("YES");
        YesAsuransiRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesAsuransiRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(NoAsuransiRadio);
        NoAsuransiRadio.setText("NO");
        NoAsuransiRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoAsuransiRadioActionPerformed(evt);
            }
        });

        jLabel22.setText("ASURANSI");

        jLabel25.setText("HARGA BARANG");

        PembayaranCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash","Credit Card","Debit Card"}));
        PembayaranCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PembayaranComboActionPerformed(evt);
            }
        });

        jLabel26.setText("METODE PEMBAYARAN");

        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel22)
                        .addGap(57, 57, 57)
                        .addComponent(YesAsuransiRadio))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(TesButton)))
                .addGap(199, 199, 199)
                .addComponent(ClearButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(BeratTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel16))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(JenisCombo, 0, 123, Short.MAX_VALUE)
                                            .addComponent(NoAsuransiRadio)
                                            .addComponent(HargaTextField))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel17)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(PembayaranCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15))))
                            .addComponent(jLabel25))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PanjangText, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(LebarText)
                            .addComponent(TinggiText))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BeratTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(PanjangText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(TinggiText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel15)
                    .addComponent(JenisCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YesAsuransiRadio)
                    .addComponent(NoAsuransiRadio)
                    .addComponent(jLabel22)
                    .addComponent(jLabel17)
                    .addComponent(LebarText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(HargaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(PembayaranCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TesButton)
                    .addComponent(ClearButton))
                .addGap(28, 28, 28))
        );

        jLabel44.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("DELIVERY SERVICE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KodePosPenerimaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KodePosPenerimaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KodePosPenerimaTextFieldActionPerformed

    private void TesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TesButtonActionPerformed
        // TODO add your handling code here:
        try {
            getPengirim().setPengirimNama(NamaPengirimTextField.getText());
            getPengirim().setPengirimAlamat(AlamatPengirimTextField.getText());
            getPengirim().setPengirimKota(KotaPengirimTextField.getText());
            getPengirim().setPengirimTelp(PengirimTelpTextField.getText());
            getPengirim().setPengirimProvinsi(String.valueOf(ProvinsiPengirimTextField.getText()));
            getPengirim().setPengirimKodePos(KodePosPengirimTextField.getText());
            
            
            getPenerima().setPenerimaNama(NamaPenerimaTextField.getText());
            getPenerima().setPenerimaTelp(PenerimaTelpTextField.getText());
            getPenerima().setPenerimaAlamat(AlamatPenerimaTextField.getText());
            getPenerima().setPenerimaKota(KotaPenerimaTextField.getText());
            getPenerima().setPenerimaKodePos(KodePosPenerimaTextField.getText());
            getPenerima().setPenerimaProvinsi(String.valueOf(TujuanDataCombo.getSelectedItem()));
            
            getPerhitungan().setBerat(Double.parseDouble(BeratTextField.getText()));
            getPerhitungan().setPanjang(Double.parseDouble(PanjangText.getText()));
            getPerhitungan().setLebar(Double.parseDouble(LebarText.getText()));
            getPerhitungan().setTinggi(Double.parseDouble(TinggiText.getText()));
            getPerhitungan().setHargaBarang(Double.parseDouble(HargaTextField.getText()));
            getPerhitungan().setJenispaket(String.valueOf(JenisCombo.getSelectedItem()));
            getPerhitungan().setPembayaran(String.valueOf(PembayaranCombo.getSelectedItem()));
            getPerhitungan().hitungDimensi();
            DimensiText.setText(String.valueOf(getPerhitungan().getDimensi()));
            getPerhitungan().setTujuan(String.valueOf(TujuanDataCombo.getSelectedItem()));
            
            if (YesAsuransiRadio.isSelected()) {
                getPerhitungan().setAsuransi(true);
        }else if (NoAsuransiRadio.isSelected()) {
                getPerhitungan().setAsuransi(false);
        }
            
            String jenis = String.valueOf(JenisCombo.getSelectedItem());
                    if (jenis.equalsIgnoreCase("reguler")) {
                        getPerhitungan().selectTarifReguler();
                        getPerhitungan().hitungBiayaKirim();
                        getPerhitungan().hitungHargaAsuransi();
                        perhitungan.setResipaket("P1");
                        
                        BiayaTextField.setText("Rp "+getPerhitungan().hitungbiayaTotal());
                    }else if (jenis.equalsIgnoreCase("cepat")) {
                        getPerhitungan().selectTarifCepat();
                        getPerhitungan().hitungBiayaKirim();
                        getPerhitungan().hitungHargaAsuransi();
                        perhitungan.setResipaket("P2");
                        
                        BiayaTextField.setText("Rp "+getPerhitungan().hitungbiayaTotal());
                    }else if (jenis.equalsIgnoreCase("express")) {
                        getPerhitungan().selectTarifExpress();
                        getPerhitungan().hitungBiayaKirim();
                        getPerhitungan().hitungHargaAsuransi();
                        perhitungan.setResipaket("P3");
                        
                        BiayaTextField.setText("Rp "+getPerhitungan().hitungbiayaTotal());
                    }else if (jenis.equalsIgnoreCase("tommorow")) {
                        getPerhitungan().selectTarifTommorow();
                        getPerhitungan().hitungBiayaKirim();
                        getPerhitungan().hitungHargaAsuransi();
                        perhitungan.setResipaket("P4");
                        
                        BiayaTextField.setText("Rp "+getPerhitungan().hitungbiayaTotal());
                    }else if (jenis.equalsIgnoreCase("sameday")) {
                        getPerhitungan().selectTarifSameday();
                        getPerhitungan().hitungBiayaKirim();
                        getPerhitungan().hitungHargaAsuransi();
                        perhitungan.setResipaket("P5");
                        
                        BiayaTextField.setText("Rp "+getPerhitungan().hitungbiayaTotal());
                    }
                    
                    //jDialog
                    jDialog1.pack();    
                    jDialog1.setVisible(true);
                    NamaPengirimTextField1.setText(NamaPengirimTextField.getText());
                    PengirimTelpTextField1.setText(PengirimTelpTextField.getText());
                    AlamatPengirimTextField1.setText(AlamatPengirimTextField.getText());
                    KotaPengirimTextField1.setText(KotaPengirimTextField.getText());
                    ProvinsiPengirimTextField1.setText(ProvinsiPengirimTextField.getText());
                    KodePosPengirimTextField1.setText(KodePosPengirimTextField.getText());
                    
                    NamaPenerimaTextField1.setText(NamaPenerimaTextField.getText());
                    PenerimaTelpTextField1.setText(PenerimaTelpTextField.getText());
                    AlamatPenerimaTextField1.setText(AlamatPenerimaTextField.getText());
                    KotaPenerimaTextField1.setText(KotaPenerimaTextField.getText());
                    ProvinsiPenerimaTextField1.setText(String.valueOf(TujuanDataCombo.getSelectedItem()));
                    KodePosPenerimaTextField1.setText(KodePosPenerimaTextField.getText());
                    
                    //pembuatan resi kirim
                    perhitungan.buatResi();
                    ResiTextField.setText(perhitungan.getResi());
                    
        } catch (Exception e) {
        }
            TarifTextField.setText(String.valueOf("Rp "+getPerhitungan().getTarifterpilih()));
                
                
            
        
        
    }//GEN-LAST:event_TesButtonActionPerformed

    private void YesAsuransiRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesAsuransiRadioActionPerformed
        // TODO add your handling code here:
        HargaTextField.setEditable(true);
    }//GEN-LAST:event_YesAsuransiRadioActionPerformed

    private void NoAsuransiRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoAsuransiRadioActionPerformed
        // TODO add your handling code here:
        HargaTextField.setEditable(false);
    }//GEN-LAST:event_NoAsuransiRadioActionPerformed

    private void LebarTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LebarTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LebarTextActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here:
        PengirimTelpTextField.setText("");
        NamaPengirimTextField.setText("");
        AlamatPengirimTextField.setText("");
        KotaPengirimTextField.setText("");
        ProvinsiPengirimTextField.setText("");
        KodePosPengirimTextField.setText("");
        
        NamaPenerimaTextField.setText("");
        PenerimaTelpTextField.setText("");
        AlamatPenerimaTextField.setText("");
        KotaPenerimaTextField.setText("");
        TujuanDataCombo.setSelectedIndex(0);
        KodePosPenerimaTextField.setText("");
        
        BeratTextField.setText("");
        JenisCombo.setSelectedIndex(0);
        YesAsuransiRadio.setSelected(false);
        NoAsuransiRadio.setSelected(false);
        HargaTextField.setText("");
        PanjangText.setText("");
        LebarText.setText("");
        TinggiText.setText("");
        DimensiText.setText("");
        PembayaranCombo.setSelectedIndex(0);
        TarifTextField.setText("");
        BiayaTextField.setText("");
        
        
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void PengirimTelpTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PengirimTelpTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PengirimTelpTextField1ActionPerformed

    private void KodePosPenerimaTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KodePosPenerimaTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KodePosPenerimaTextField1ActionPerformed

    private void PembayaranComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PembayaranComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PembayaranComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiPengirimanBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiPengirimanBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiPengirimanBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiPengirimanBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AplikasiPengirimanBarang().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AlamatPenerimaTextField;
    private javax.swing.JTextField AlamatPenerimaTextField1;
    private javax.swing.JTextField AlamatPengirimTextField;
    private javax.swing.JTextField AlamatPengirimTextField1;
    private javax.swing.JTextField BeratTextField;
    private javax.swing.JTextField BiayaTextField;
    private javax.swing.JButton ClearButton;
    private javax.swing.JTextField DimensiText;
    private javax.swing.JTextField HargaTextField;
    private javax.swing.JComboBox<String> JenisCombo;
    private javax.swing.JTextField KodePosPenerimaTextField;
    private javax.swing.JTextField KodePosPenerimaTextField1;
    private javax.swing.JTextField KodePosPengirimTextField;
    private javax.swing.JTextField KodePosPengirimTextField1;
    private javax.swing.JTextField KotaPenerimaTextField;
    private javax.swing.JTextField KotaPenerimaTextField1;
    private javax.swing.JTextField KotaPengirimTextField;
    private javax.swing.JTextField KotaPengirimTextField1;
    private javax.swing.JTextField LebarText;
    private javax.swing.JTextField NamaPenerimaTextField;
    private javax.swing.JTextField NamaPenerimaTextField1;
    private javax.swing.JTextField NamaPengirimTextField;
    private javax.swing.JTextField NamaPengirimTextField1;
    private javax.swing.JRadioButton NoAsuransiRadio;
    private javax.swing.JTextField PanjangText;
    private javax.swing.JComboBox<String> PembayaranCombo;
    private javax.swing.JTextField PenerimaTelpTextField;
    private javax.swing.JTextField PenerimaTelpTextField1;
    private javax.swing.JTextField PengirimTelpTextField;
    private javax.swing.JTextField PengirimTelpTextField1;
    private javax.swing.JTextField ProvinsiPenerimaTextField1;
    private javax.swing.JTextField ProvinsiPengirimTextField;
    private javax.swing.JTextField ProvinsiPengirimTextField1;
    private javax.swing.JTextField ResiTextField;
    private javax.swing.JTextField TarifTextField;
    private javax.swing.JButton TesButton;
    private javax.swing.JTextField TinggiText;
    private javax.swing.JComboBox<String> TujuanDataCombo;
    private javax.swing.JRadioButton YesAsuransiRadio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the dao
     */
    public TarifDAO getDao() {
        return dao;
    }

    /**
     * @param dao the dao to set
     */
    public void setDao(TarifDAO dao) {
        this.dao = dao;
    }

    /**
     * @return the pengirim
     */
    public Pengirim getPengirim() {
        return pengirim;
    }

    /**
     * @param pengirim the pengirim to set
     */
    public void setPengirim(Pengirim pengirim) {
        this.pengirim = pengirim;
    }

    /**
     * @return the penerima
     */
    public Penerima getPenerima() {
        return penerima;
    }

    /**
     * @param penerima the penerima to set
     */
    public void setPenerima(Penerima penerima) {
        this.penerima = penerima;
    }

    /**
     * @return the tarif
     */
    public Tarif getTarif() {
        return tarif;
    }

    /**
     * @param tarif the tarif to set
     */
    public void setTarif(Tarif tarif) {
        this.tarif = tarif;
    }
    
    

    /**
     * @return the perhitungan
     */
    public Perhitungan getPerhitungan() {
        return perhitungan;
    }

    /**
     * @param perhitungan the perhitungan to set
     */
    public void setPerhitungan(Perhitungan perhitungan) {
        this.perhitungan = perhitungan;
    }

    /**
     * @return the combo
     */
    public String[] getCombo() {
        return combo;
    }

    /**
     * @param combo the combo to set
     */
    public void setCombo(String[] combo) {
        this.combo = combo;
    }

    /**
     * @return the resi
     */
    
}
